FROM node:20-alpine

WORKDIR /app

ARG FRONTEND_PORT=4200
ENV PORT=$FRONTEND_PORT

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE $PORT

CMD ["sh", "-c", "npm run start -- --host 0.0.0.0 --port $PORT --poll 2000"]
