
server.port=${SERVER_PORT}

spring.application.name=gas-station-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=${SWAGGER_PATH}
springdoc.api-docs.path=${API_DOCS_PATH}

# Tabla para el control de eventos
spring.modulith.events.jdbc.schema-initialization.enabled=true
